#!/usr/bin/env node
/*
 Increments a persistent build number and writes it to src/build.json.
 Runs before the site build, so the file can be imported/consumed by the app if desired.
*/

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const buildJsonPath = path.join(process.cwd(), 'src', 'build.json');
const buildTsPath = path.join(process.cwd(), 'src', 'build.ts');

function readExistingBuildNumber(filePath) {
  try {
    if (!fs.existsSync(filePath)) return 0;
    const json = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const n = Number(json.build);
    return Number.isFinite(n) && n >= 0 ? n : 0;
  } catch {
    return 0;
  }
}

function getGitInfo() {
  try {
    const commit = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    const branch = execSync('git rev-parse --abbrev-ref HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    return { commit, branch };
  } catch {
    return { commit: null, branch: null };
  }
}

function writeBuildInfo(filePath, data) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
}

const current = readExistingBuildNumber(buildJsonPath);
const next = current + 1;
const now = new Date().toISOString();
const git = getGitInfo();

const payload = {
  build: next,
  builtAt: now,
  commit: git.commit,
  branch: git.branch,
};

writeBuildInfo(buildJsonPath, payload);
// Also emit a typed module for easy imports in TS/ Astro
const ts = `// This file is auto-generated by scripts/increment-build.cjs\n` +
`// Do not edit manually.\n` +
`export interface BuildInfo {\n` +
`  build: number;\n` +
`  builtAt: string;\n` +
`  commit: string | null;\n` +
`  branch: string | null;\n` +
`}\n` +
`export const BUILD: BuildInfo = ${JSON.stringify(payload, null, 2)} as const;\n`;
fs.writeFileSync(buildTsPath, ts, 'utf8');
console.log(`[build] Incremented build number: ${current} -> ${next}`);


